version: '3.3'

services:
  postgres:
    image: postgres:14.2-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/001.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: flask run --host=0.0.0.0 --port=8080 --reload
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
